#!/bin/bash

genA=../../bin/genA

$genA -i genA_input -p parmfile.4 -r CNX_4p.restart -s CNX_4p.scores -f CNX_4p.frcmod -y CNX_4p.fit -o CNX_4p.log  
$genA -i genA_input -p parmfile.4.1 -c CNX_4p.restart -r CNX_4p.restart1 -s CNX_4p.scores1 -f CNX_4p.frcmod1 -y CNX_4p.fit1 -o CNX_4p.log1 
$genA -i genA_input -p parmfile.4.2 -c CNX_4p.restart1 -r CNX_4p.restart2 -s CNX_4p.scores2 -f CNX_4p.frcmod2 -y CNX_4p.fit2 -o CNX_4p.log2 

